# Generated by Django 4.2.2 on 2023-06-15 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackDatabase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exception', models.CharField(max_length=255)),
                ('solution', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='InputTable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('exception', models.CharField(max_length=255)),
                ('cluster', models.CharField(max_length=255)),
                ('step', models.CharField(max_length=255)),
                ('time_taken', models.TimeField()),
                ('exception_label', models.CharField(max_length=255)),
            ],
        ),
    ]
